### ISSUE TITLE
setParams and send?

### ISSUE THREAD

**Issue by c9s** [howtomakeaturn/pay2go-invoice#1]
文件中的 `$params` 看起來 lifetime 應該是在 send() 之後就不會被使用到?

```
$pay2go->setParams($params);
$result = $pay2go->send();
```

如上 API 呼叫方式，或許改為下面方式比較乾淨?

```
$result = $pay2go->send($params);
```

**Comment by howtomakeaturn** [comment]
非常謝謝你的意見！

原API需要填入的參數非常多，對使用者來說很麻煩

我本來想多寫幾個類別協助使用者，讓他們少填B2B/B2C、稅金、TimeStamp之類的欄位

然後讓使用者除了直接設定原始參數之外，有其它更輕鬆的方法使用API

例如：

```
$order = new Order('Product Name', 1000);

$order->blah(); // 提供某些好用方法

$pay2go->setOrder($order);

$pay2go->send();
```

甚至是更漂亮的

```
$order = new Order('some name');

$order->add(new Product(1000));

$order->add(new Product(1500));

$order->setTaxRate(0.05);

$pay2go->setOrder($order);

$pay2go->send();
```

讓使用者可透過
- ->setOrder
- ->setParams
- ...blah

等等多種方式設定參數，然後統一呼叫->send送出

不過那些類別我還沒時間設計出來（加上我不知道大家習慣填稅前/稅後金額），所以乾脆就先丟出來了

這樣設計是希望預留一些擴充性，我原本的想法大概是這樣！

**Comment by c9s** [comment]
這樣的話，還是沒有衝突，你的 params 的 lifetime 只需要當作是 send 的參數處理，不需 setParams

依照 SRP 的原則，Order -> parameters 的轉換，抽象出來做 param builder 會比較好。  保留 send(array $param) 即可達到最大的擴充性。

**Comment by howtomakeaturn** [comment]
有道理，那我下一個minor release就把參數放進send好了！
謝囉！

**Comment by c9s** [comment]
Thanks!

**Comment by zx1986** [comment]
https://www.sitepoint.com/the-single-responsibility-principle/

我自己筆記一下。
